networks:
  local-network:
    driver: bridge

services:
  database:
    container_name: postgres-dev
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user.dev@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - local-network

volumes:
  pgdata:
